name: AdminRage
main: tempelchat.AdminRage.AdminRage
version: 1.7
commands:
    adminrage:
        description: Something really bad happens, if you offend an admin!
        usage:
            /adminrage
            /ar